# -*- coding: utf-8 -*-
"""Untitled0.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1dTNXTYDvy4n0wfTice3n669Lb4rMsA1E
"""

from pandas.core.common import random_state
import numpy as np 
import pandas as pd 
import matplotlib.pyplot as plt 

url = 'https://raw.githubusercontent.com/basakesin/Bootcampizmir-Datasets/master/HR.csv'

dataset = pd.read_csv(url)
print(dataset.shape)

dataset.head(5)

y = dataset["left"]
 
x = dataset.loc[:, dataset.columns != 'left']

from sklearn.preprocessing import LabelEncoder
labelencoder = LabelEncoder()

x["sales"] = labelencoder.fit_transform(x["sales"])
x["salary"] = labelencoder.fit_transform(x["salary"])

x.head(5)

from sklearn.model_selection import train_test_split
x_train, x_test, y_train, y_test = train_test_split (x,y, test_size = 0.3, random_state = 0)

from sklearn.preprocessing import StandardScaler
sc = StandardScaler()
x_train = sc.fit_transform(x_train)
x_test = sc.transform(x_test)

from sklearn import model_selection
from sklearn.metrics import classification_report
from sklearn.metrics import confusion_matrix

print(x_train.shape)
print(x_test.shape)

from sklearn import svm

clf = svm.SVC()
clf.fit(x_train, y_train)
y_predict = clf.predict(x_test)

from sklearn.metrics import confusion_matrix

confusion_matrix(y_test, y_predict)

from sklearn.metrics import accuracy_score

accuracy_score(y_test, y_predict)

from sklearn.neighbors import KNeighborsClassifier

neigh = KNeighborsClassifier(n_neighbors=2)

neigh.fit(x_train , y_train)

y_predict = neigh.predict(x_test)

from sklearn.metrics import confusion_matrix

confusion_matrix(y_test, y_predict)

from sklearn.metrics import accuracy_score

accuracy_score(y_test, y_predict)



